[phases.setup]
aptPkgs = [
    "google-chrome-stable",
    "chromium-chromedriver",
    "xvfb",
    "wget",
    "gnupg",
    "unzip",
    "ca-certificates",
    "apt-transport-https",
    "software-properties-common"
]

[phases.build]
cmds = [
    "wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -",
    "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list",
    "apt-get update",
    "apt-get install -y google-chrome-stable chromium-chromedriver",
    "ln -sf /usr/bin/chromedriver /usr/local/bin/chromedriver",
    "pip install -r requirements.txt"
]

[start]
cmd = "python start_railway.py"
