[phases.setup]
aptPkgs = [
    "wget",
    "gnupg",
    "ca-certificates",
    "apt-transport-https",
    "software-properties-common",
    "xvfb",
    "unzip",
    "curl"
]

[phases.build]
cmds = [
    "wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -",
    "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list",
    "apt-get update",
    "apt-get install -y google-chrome-stable",
    "wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip",
    "unzip /tmp/chromedriver.zip -d /tmp/",
    "mv /tmp/chromedriver /usr/local/bin/chromedriver",
    "chmod +x /usr/local/bin/chromedriver",
    "rm /tmp/chromedriver.zip",
    "pip install -r requirements.txt"
]

[start]
cmd = "python start_railway.py"
